### ISSUE TITLE
Request<T> should put the namespace

### ISSUE THREAD

**Issue by sonpham1994** [what3words/w3w-dotnet-wrapper#14]
Hi guys, could you put the namespace for the `Request<T>` abstract class here? 
https://github.com/what3words/w3w-dotnet-wrapper/blob/d2188e9eb4e485c3ecb2940cb7a92cecc20d51f5/what3words.dotnet.wrapper/request/IW3WRequests.cs

The `Request<T>` from `w3w-dotnet-wrapper` can be recognized even I don't specify `using what3words.dotnet.wrapper` in my class and it makes a lot of conflicts in many classes from my project, because my project also uses another class called `Request<T>`

**Comment by chaddgrimm** [comment]
@sonpham1994 Thanks for bringing this to our attention. I'll publish a fix soon and let you know.

**Comment by chaddgrimm** [comment]
@sonpham1994 [4.0.0](https://www.nuget.org/packages/what3words.dotnet.wrapper/4.0.0) has been released
