### ISSUE TITLE
Refit 6.0.24 Vulnerable

### ISSUE THREAD

**Issue by administersoftware** [what3words/w3w-dotnet-wrapper#16]
Visual Studio is now reporting Refit 6.0.24 has a known critical severity vulnerability :(

**Comment by chaddgrimm** [comment]
@administersoftware thanks for reporting this. We've been wanting to remove Refit as a dependency for some time now. We'll be publishing another version that'll no longer have Refit.

**Comment by administersoftware** [comment]
Thank you - Great news.

**Comment by chaddgrimm** [comment]
@administersoftware [v4.1.0](https://www.nuget.org/packages/what3words.dotnet.wrapper/4.1.0) has been released. Let us know if this works for you. Thanks! 🎉

**Comment by administersoftware** [comment]
Thank you, all builds, runs and no vulnerable package warning :)
