### ISSUE TITLE
Wrapper not giving correct results with non English culture

### ISSUE THREAD

**Issue by stevegdavis** [what3words/w3w-dotnet-wrapper#3]
I have created a very simple Xamarin Forms Android app that makes a call to ConvertTo3WA and the method returns the correct result as expected when the phone culture is English, however if I set the phone to say French language the call fails with the result saying:-
BadCoordinates - coordinates must be two comma separated lat,lng coordinates

My simple code:-
var wrapper = new What3WordsV3("xxxxxxxx");
            var result = await wrapper.ConvertTo3WA(new Coordinates(51.222011, 0.152311)).RequestAsync();
            if (result.IsSuccessful)
            {
                LabelConvertTo3wa.Text = "3 word address: " + result.Data.Words;
                LabelConvertTo3waCountry.Text = "Country: " + result.Data.Country;
                LabelConvertTo3waNearestPlace.Text = "Nearsest Place: " + result.Data.NearestPlace;
            }
            else
            {
                LabelConvertTo3wa.Text = result.Error.Code + " - " + result.Error.Message;
LabelConvertTo3waCountry.Text = "";
LabelConvertTo3waNearestPlace.Text = "";
            }

Thanks.

**Comment by andycurriew3w** [comment]
Hi @stevegdavis ,

Thank you for the message. We'll investigate and get back to you asap.

Regards,

Andy

**Comment by stevegdavis** [comment]
Hi @andycurriew3w,
Many thanks for the quick response, I will look forward to the fix.

**Comment by andycurriew3w** [comment]
Hi @stevegdavis ,

We've released a pre-release here: https://www.nuget.org/packages/what3words.dotnet.wrapper/3.0.4-beta with a fix. Would you be able to confirm if this fixes your issue?

Many thanks,

Andy

**Comment by stevegdavis** [comment]
Hi @andycurriew3w,
Yes it is fixed, many thanks, shall I close the issue?

**Comment by andycurriew3w** [comment]
Thanks for letting me know. I'll close ticket
