### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by curtisy1** [what3words/w3w-dotnet-wrapper#6]
This project is missing a license, specifying usage conditions. [The node wrapper](https://github.com/what3words/w3w-node-wrapper/blob/master/LICENCE.md) uses MIT for this, so probably MIT would be fine here too?

To clarify why this is needed: According to [the open source guide](https://opensource.guide/legal/) Section 2 states
> If you don’t apply an open source license, everybody who contributes to your project also becomes an exclusive copyright holder of their work. That means nobody can use, copy, distribute, or modify their contributions – and that “nobody” includes you.

So for commercial use, the wrapper is not actually usable from an open source point of view as it doesn't grant any usage rights in itself

**Comment by andycurriew3w** [comment]
Hi @curtisy1 , Thank you for raising. I've created a ticket to add the MIT licence.
